// AUTO-GENERATED from @vscode/codicons metadata (dist/metadata.json) — do NOT edit by
// hand. Regenerate with the codicon catalog generator when the codicons package is
// upgraded. Every id here is a real product icon (it came straight from the icon font's
// own metadata), so the "verify every ThemeIcon id" rule is satisfied by construction.
//
// This is the single source of truth for the icon set offered by the Customize panel and
// the Quick icon QuickPick. ICON_CATEGORIES drives the grouped display order (each id maps
// to a customize.iconGroup.<id> label); ICON_KEYWORDS are search-match aids taken from the
// upstream icon metadata (tags + description), not display prose — they are matched as the
// user types but never shown as a translated string, so they live here rather than in the
// l10n catalog. 536 icons across 28 categories.

export interface IconCategory {
  // The codicon metadata category id; the panel maps it to a customize.iconGroup.<id> label.
  id: string;
  // The icon ids in this category, in the icon font's own order.
  ids: readonly string[];
}

export const ICON_CATEGORIES: readonly IconCategory[] = [
  { id: "file", ids: ["archive", "file", "file-code", "files", "folder", "folder-opened", "new-file", "new-folder", "file-binary", "file-media", "file-pdf", "file-symlink-directory", "file-symlink-file", "file-text", "file-zip", "folder-active", "folder-library", "notebook-template", "root-folder", "root-folder-opened", "unarchive"] },
  { id: "development", ids: ["code", "json", "markdown", "notebook", "output", "package", "build", "edit-code", "mcp", "references", "surround-with", "type-hierarchy", "type-hierarchy-sub", "type-hierarchy-super"] },
  { id: "symbol", ids: ["symbol-class", "symbol-method", "array", "bracket-dot", "bracket-error", "index-zero", "percentage", "symbol-boolean", "symbol-color", "symbol-constant", "symbol-enum", "symbol-enum-member", "symbol-field", "symbol-file", "symbol-interface", "symbol-key", "symbol-keyword", "symbol-method-arrow", "symbol-misc", "symbol-module", "symbol-numeric", "symbol-operator", "symbol-parameter", "symbol-property", "symbol-reference", "symbol-ruler", "symbol-snippet", "symbol-string", "symbol-structure", "variable", "variable-group"] },
  { id: "text", ids: ["bold", "text-size", "horizontal-rule", "indent", "italic", "keyboard-tab", "keyboard-tab-above", "keyboard-tab-below", "newline", "no-newline", "quote", "quotes", "strikethrough", "whitespace", "word-wrap"] },
  { id: "content", ids: ["book", "checklist", "list-ordered", "list-unordered", "note", "list-flat", "list-selection", "list-tree", "table", "tasklist"] },
  { id: "action", ids: ["add", "bookmark", "check-all", "clear-all", "clippy", "close", "close-all", "cloud-download", "cloud-upload", "collapse-all", "copy", "edit", "eye", "eye-closed", "filter", "link-external", "merge", "mirror", "move", "new-session", "pin", "play", "preview", "record", "redo", "refresh", "remove", "replace", "save", "save-all", "trash", "watch", "zoom-in", "zoom-out", "add-small", "arrow-swap", "attach", "clone", "combine", "discard", "download", "edit-session", "eraser", "exclude", "expand-all", "export", "filter-filled", "fold", "fold-down", "fold-up", "go-to-editing-session", "grabber", "gripper", "group-by-ref-type", "insert", "lightbulb-autofix", "list-filter", "open-in-product", "open-in-window", "open-preview", "pinned", "pinned-dirty", "play-circle", "record-keys", "record-small", "remove-small", "rename", "replace-all", "run-above", "run-all", "run-below", "run-with-deps", "save-as", "screen-cut", "share", "skip", "sort-precedence", "stop-circle", "sync-ignored", "unfold", "ungroup-by-ref-type"] },
  { id: "navigation", ids: ["arrow-both", "arrow-circle-down", "arrow-circle-left", "arrow-circle-right", "arrow-circle-up", "arrow-down", "arrow-left", "arrow-right", "arrow-up", "chevron-down", "chevron-left", "chevron-right", "chevron-up", "home", "menu", "more", "arrow-small-down", "arrow-small-left", "arrow-small-right", "arrow-small-up", "compass", "compass-active", "compass-dot", "forward", "kebab-vertical", "three-bars"] },
  { id: "search", ids: ["case-sensitive", "regex", "search", "go-to-search", "preserve-case", "search-fuzzy", "search-large", "search-stop", "telescope", "whole-word"] },
  { id: "git", ids: ["diff", "diff-added", "diff-ignored", "diff-modified", "diff-removed", "diff-renamed", "git-branch", "git-commit", "git-merge", "git-pull-request", "repo", "source-control", "code-review", "diff-multiple", "diff-single", "file-submodule", "gist", "gist-fork", "gist-private", "gist-secret", "git-branch-changes", "git-branch-conflicts", "git-branch-staged-changes", "git-compare", "git-pull-request-closed", "git-pull-request-create", "git-pull-request-done", "git-pull-request-draft", "git-pull-request-go-to-changes", "git-pull-request-new-changes", "git-stash", "git-stash-apply", "git-stash-pop", "github-action", "github-project", "issue-draft", "issue-reopened", "merge-into", "repo-clone", "repo-fetch", "repo-force-push", "repo-pinned", "repo-pull", "repo-push", "repo-selected", "repo-sync", "request-changes", "versions"] },
  { id: "debug", ids: ["activate-breakpoints", "bug", "debug", "debug-alt", "debug-console", "coverage", "debug-all", "debug-alt-small", "debug-breakpoint-conditional", "debug-breakpoint-conditional-unverified", "debug-breakpoint-data", "debug-breakpoint-data-unverified", "debug-breakpoint-function", "debug-breakpoint-function-unverified", "debug-breakpoint-log", "debug-breakpoint-log-unverified", "debug-breakpoint-unsupported", "debug-connected", "debug-continue", "debug-continue-small", "debug-coverage", "debug-disconnect", "debug-line-by-line", "debug-pause", "debug-rerun", "debug-restart", "debug-restart-frame", "debug-reverse-continue", "debug-stackframe", "debug-stackframe-active", "debug-start", "debug-step-back", "debug-step-into", "debug-step-out", "debug-step-over", "debug-stop", "inspect", "run-all-coverage", "run-coverage", "run-errors"] },
  { id: "tool", ids: ["beaker", "circuit-board", "beaker-stop", "magnet", "paintcan", "tools", "wand"] },
  { id: "settings", ids: ["color-mode", "gear", "settings", "settings-gear"] },
  { id: "layout", ids: ["split-horizontal", "split-vertical", "window", "editor-layout", "layers", "layers-active", "layers-dot", "layout", "layout-activitybar-left", "layout-activitybar-right", "layout-centered", "layout-menubar", "layout-panel", "layout-panel-center", "layout-panel-dock", "layout-panel-justify", "layout-panel-left", "layout-panel-off", "layout-panel-right", "layout-sidebar-left", "layout-sidebar-left-dock", "layout-sidebar-left-off", "layout-sidebar-right", "layout-sidebar-right-dock", "layout-sidebar-right-off", "layout-statusbar"] },
  { id: "window", ids: ["chrome-close", "chrome-maximize", "chrome-minimize", "chrome-restore", "empty-window", "multiple-windows", "screen-full", "screen-normal", "window-active"] },
  { id: "application", ids: ["browser", "dashboard", "extensions", "terminal", "extensions-large", "terminal-bash", "terminal-cmd", "terminal-debian", "terminal-git-bash", "terminal-linux", "terminal-powershell", "terminal-tmux", "terminal-ubuntu"] },
  { id: "device", ids: ["device-camera", "device-camera-video", "device-mobile", "mic", "chip", "mic-filled", "mute", "unmute", "vm", "vm-active", "vm-connect", "vm-outline", "vm-running", "vm-small", "vr"] },
  { id: "storage", ids: ["cloud", "database", "cloud-small"] },
  { id: "connection", ids: ["remote", "remote-explorer", "send-to-remote-agent"] },
  { id: "communication", ids: ["ask", "broadcast", "call-incoming", "call-outgoing", "comment", "comment-discussion", "mail", "comment-discussion-quote", "comment-draft", "comment-unresolved", "feedback", "inbox", "live-share", "mail-read", "mail-reply", "megaphone", "mention", "radio-tower", "reactions", "rss", "send"] },
  { id: "notification", ids: ["bell", "bell-dot", "bell-slash", "bell-slash-dot"] },
  { id: "user", ids: ["account", "organization", "person", "log-in", "log-out", "person-add"] },
  { id: "status", ids: ["check", "circle-slash", "error", "info", "loading", "pass", "verified", "workspace-trusted", "alert", "error-small", "flag", "flame", "pass-filled", "pulse", "session-in-progress", "unverified", "verified-filled", "workspace-unknown", "workspace-untrusted"] },
  { id: "security", ids: ["key", "shield", "unlock", "lock-small"] },
  { id: "shape", ids: ["circle-filled", "circle-large-filled", "circle-large", "circle-outline", "circle-small", "circle-small-filled", "primitive-square", "triangle-down", "triangle-left", "triangle-right", "triangle-up"] },
  { id: "visualization", ids: ["graph", "graph-left", "graph-line", "graph-scatter", "pie-chart"] },
  { id: "brand", ids: ["azure", "azure-devops", "code-oss", "github-alt", "github-inverted", "logo-github", "octoface", "python", "ruby", "twitter", "vscode", "vscode-insiders"] },
  { id: "ai", ids: ["copilot", "sparkle", "agent", "chat-sparkle", "chat-sparkle-error", "chat-sparkle-warning", "comment-discussion-sparkle", "copilot-blocked", "copilot-error", "copilot-in-progress", "copilot-large", "copilot-not-connected", "copilot-snooze", "copilot-success", "copilot-unavailable", "copilot-warning", "copilot-warning-large", "edit-sparkle", "hubot", "lightbulb-sparkle", "robot", "search-sparkle", "sparkle-filled", "thinking"] },
  { id: "general", ids: ["briefcase", "calendar", "coffee", "credit-card", "dash", "globe", "heart", "issues", "law", "library", "lightbulb", "link", "location", "plug", "project", "question", "report", "rocket", "server", "star", "tag", "blank", "clockface", "collection", "collection-small", "cursor", "game", "gift", "heart-filled", "history", "jersey", "lightbulb-empty", "map", "map-filled", "map-vertical", "map-vertical-filled", "milestone", "mortar-board", "music", "new-collection", "piano", "server-environment", "server-process", "smiley", "snake", "squirrel", "star-full", "star-half", "target", "thumbsdown", "thumbsdown-filled", "thumbsup", "thumbsup-filled", "zap"] },
];

// Every offered icon id, flattened — used to validate a stored icon and to seed search.
export const ALL_ICON_IDS: readonly string[] = ICON_CATEGORIES.flatMap((c) => c.ids);

// id -> space-joined search keywords (lowercase, de-duplicated, id tokens removed).
export const ICON_KEYWORDS: Readonly<Record<string, string>> = {
  "account": "person people face user contact profile avatar",
  "activate-breakpoints": "debug dot circle toggle switch enable",
  "add": "plus new create combine more insert item",
  "add-small": "plus new create mini tiny",
  "agent": "ai bot assistant robot service",
  "alert": "warning error danger notification triangle exclamation",
  "archive": "save box delivery package store compress items",
  "array": "list collection brackets data structure",
  "arrow-both": "switch swap exchange bidirectional transfer",
  "arrow-circle-down": "download direction navigate round circular pointing",
  "arrow-circle-left": "back direction navigate round previous circular pointing",
  "arrow-circle-right": "forward direction navigate round next circular pointing",
  "arrow-circle-up": "upload direction navigate round circular pointing",
  "arrow-down": "direction navigate sort download descend pointing",
  "arrow-left": "direction navigate back previous pointing",
  "arrow-right": "direction navigate forward next pointing",
  "arrow-small-down": "direction navigate mini tiny descend pointing",
  "arrow-small-left": "direction navigate back mini tiny pointing",
  "arrow-small-right": "direction navigate forward mini tiny pointing",
  "arrow-small-up": "direction navigate mini tiny ascend pointing",
  "arrow-swap": "switch exchange replace direction arrows",
  "arrow-up": "direction navigate sort upload ascend pointing",
  "ask": "question help chat inquiry support message bubble mark",
  "attach": "clip paperclip file link connect add item",
  "azure": "cloud microsoft service platform logo",
  "azure-devops": "cloud microsoft service cicd logo",
  "beaker": "test lab tube science experiment flask testing experimental feature",
  "beaker-stop": "test experiment halt cancel lab",
  "bell": "alert notify notification alarm reminder",
  "bell-dot": "alert notify notification alarm unread badge",
  "bell-slash": "mute silent quiet no-notification off notifications disabled",
  "bell-slash-dot": "mute silent quiet unread badge notifications disabled",
  "blank": "empty nothing void clear space",
  "bold": "text format weight font style strong formatting",
  "book": "library text read documentation manual guide reading material",
  "bookmark": "save mark favorite remember flag later",
  "bracket-dot": "code json array badge",
  "bracket-error": "code json array issue problem",
  "briefcase": "work workplace business professional job related",
  "broadcast": "tower signal connect connection transmit wireless",
  "browser": "web internet page window site webpage",
  "bug": "error issue insect problem defect",
  "build": "compile make construct tools hammer",
  "calendar": "day time week month date schedule event planner",
  "call-incoming": "phone voice connection receive",
  "call-outgoing": "phone voice connection send",
  "case-sensitive": "search filter option letters words text",
  "chat-sparkle": "ai copilot message magic suggestion",
  "chat-sparkle-error": "ai copilot message issue problem",
  "chat-sparkle-warning": "ai copilot message alert caution exclamation",
  "check": "checkmark select checked mark complete finish done accept approve success",
  "check-all": "checkmark select everything checked mark complete finish done accept approve bulk",
  "checklist": "checkmark select checked mark complete finish done todo task list",
  "chevron-down": "twistie tree node folder fold collapse expand dropdown pointing",
  "chevron-left": "twistie tree node folder fold collapse back pointing",
  "chevron-right": "twistie tree node folder fold expand forward pointing",
  "chevron-up": "twistie tree node folder fold collapse expand pointing",
  "chip": "hardware processor cpu gpu silicon integrated computer",
  "chrome-close": "menu bar window dismiss exit quit",
  "chrome-maximize": "menu bar window large increase expand",
  "chrome-minimize": "menu bar window small decrease reduce",
  "chrome-restore": "menu bar window resize normal",
  "circle-filled": "dot round small bullet point breakpoint",
  "circle-large": "dot round bullet point outline",
  "circle-large-filled": "dot round bullet point",
  "circle-outline": "round shape empty ring hollow",
  "circle-slash": "error block stop disable prohibited forbidden blocked disabled",
  "circle-small": "dot point round tiny mini outline",
  "circle-small-filled": "dot point round tiny mini solid",
  "circuit-board": "iot device process hardware technology",
  "clear-all": "reset remove delete clean empty",
  "clippy": "clipboard document edit copy paste",
  "clockface": "time watch schedule history wait hour minute clock face showing",
  "clone": "copy duplicate replicate git repo",
  "close": "remove delete cancel stop dismiss exit",
  "close-all": "remove bulk dismiss exit items",
  "cloud": "online service storage sync remote",
  "cloud-download": "install import retrieve fetch from",
  "cloud-small": "online storage mini tiny remote",
  "cloud-upload": "export save send publish",
  "code": "embed script programming development source",
  "code-oss": "vscode open source editor logo brand",
  "code-review": "pr pull request check inspect examine",
  "coffee": "break drink beverage java pause time",
  "collapse-all": "bulk fold minimize hide tree items",
  "collection": "group set library stack gather items",
  "collection-small": "group set library mini tiny",
  "color-mode": "switch dark light contrast theme toggle",
  "combine": "merge join unite mix blend items",
  "comment": "dialog message bubble chat feedback note",
  "comment-discussion": "dialog message bubble chat conversation feedback",
  "comment-discussion-quote": "chat reply reference cite message quoted",
  "comment-discussion-sparkle": "ai chat copilot magic suggestion intelligent",
  "comment-draft": "message unsaved pending write edit pr",
  "comment-unresolved": "message open pending issue active pr",
  "compass": "navigate direction orient guide map navigation",
  "compass-active": "navigate direction orient guide",
  "compass-dot": "navigate direction orient badge notification",
  "copilot": "ai assistant help automation suggestion",
  "copilot-blocked": "ai stop prevent ban restricted intelligent agent",
  "copilot-error": "ai issue problem fail bug cross intelligent agent",
  "copilot-in-progress": "ai loading thinking working busy spinner waiting intelligent agent",
  "copilot-large": "ai assistant big logo brand intelligent agent",
  "copilot-not-connected": "ai offline disconnected network link intelligent agent",
  "copilot-snooze": "ai sleep pause wait later intelligent agent snoozed",
  "copilot-success": "ai check done complete ok intelligent agent tick pass",
  "copilot-unavailable": "ai offline missing gone disabled intelligent agent",
  "copilot-warning": "ai alert caution attention issue exclamation intelligent agent",
  "copilot-warning-large": "ai alert caution big attention exclamation intelligent agent",
  "copy": "duplicate clone clipboard paste content",
  "coverage": "test percent code quality metrics",
  "credit-card": "payment merchant money billing purchase",
  "cursor": "pointer mouse click select arrow",
  "dash": "line minus subtract hyphen separator",
  "dashboard": "panel stats dial overview metrics",
  "database": "sql storage data server table",
  "debug": "run test troubleshoot fix breakpoint",
  "debug-all": "run test everything suite batch play",
  "debug-alt": "run execute play start alternative",
  "debug-alt-small": "run play mini tiny start execute",
  "debug-breakpoint-conditional": "stop pause if logic test",
  "debug-breakpoint-conditional-unverified": "stop pause if grey inactive",
  "debug-breakpoint-data": "stop pause variable value watch",
  "debug-breakpoint-data-unverified": "stop pause variable grey inactive",
  "debug-breakpoint-function": "stop pause method call triangle",
  "debug-breakpoint-function-unverified": "stop pause method grey inactive",
  "debug-breakpoint-log": "print message console diamond record logpoint",
  "debug-breakpoint-log-unverified": "print message grey inactive diamond logpoint",
  "debug-breakpoint-unsupported": "stop error invalid broken fail exclamation",
  "debug-connected": "attach link online active plug debugger",
  "debug-console": "terminal command input compile build output",
  "debug-continue": "play resume next forward run debugging",
  "debug-continue-small": "play resume mini tiny run",
  "debug-coverage": "test percent metrics quality report",
  "debug-disconnect": "stop unplug detach offline end debugger",
  "debug-line-by-line": "step walk trace flow execute",
  "debug-pause": "break halt wait freeze stop debugging",
  "debug-rerun": "restart again repeat loop reload session",
  "debug-restart": "reload reset again cycle refresh debugging",
  "debug-restart-frame": "stack reset up back context",
  "debug-reverse-continue": "back rewind previous undo return",
  "debug-stackframe": "call layer context memory trace stack frame",
  "debug-stackframe-active": "call layer current now focus stack frame",
  "debug-start": "run play launch begin execute debugging",
  "debug-step-back": "reverse previous undo return rewind arrow",
  "debug-step-into": "enter down inside drill call arrow",
  "debug-step-out": "exit up return leave escape",
  "debug-step-over": "next skip jump forward pass",
  "debug-stop": "terminate end kill halt finish exit square debugging",
  "device-camera": "capture picture image photo screenshot",
  "device-camera-video": "movie record capture film",
  "device-mobile": "phone handheld smartphone responsive",
  "diff": "compare changes difference git version comparison",
  "diff-added": "git change new insert green changes",
  "diff-ignored": "git change skip excluded changes",
  "diff-modified": "git change edit updated yellow changes",
  "diff-multiple": "compare changes files batch many git pr diffs",
  "diff-removed": "git change delete red changes",
  "diff-renamed": "git change move changes",
  "diff-single": "compare change file one individual git pr",
  "discard": "undo revert throw trash cancel delete changes",
  "download": "get retrieve save install pull cloud",
  "edit": "pencil modify write change update",
  "edit-code": "write modify script program change",
  "edit-session": "work context state save restore",
  "edit-sparkle": "ai magic auto fix refactor smart intelligent",
  "editor-layout": "split grid view arrange window",
  "empty-window": "blank new clear frame start",
  "eraser": "delete remove clear rub clean",
  "error": "stop problem issue alert warning critical",
  "error-small": "issue problem bug mini tiny cross",
  "exclude": "remove hide filter minus ban item",
  "expand-all": "open show unfold reveal tree items",
  "export": "save send out download extract data",
  "extensions": "plugin addon package module marketplace plugins",
  "extensions-large": "plugins addons marketplace big",
  "eye": "view watch see visibility preview",
  "eye-closed": "hide hidden invisible privacy conceal",
  "feedback": "comment review opinion rate message",
  "file": "document text page content",
  "file-binary": "data raw executable blob 01",
  "file-code": "source programming script development",
  "file-media": "image video audio picture movie",
  "file-pdf": "document adobe print read paper",
  "file-submodule": "git repo link reference external",
  "file-symlink-directory": "link shortcut alias folder pointer",
  "file-symlink-file": "link shortcut alias document pointer",
  "file-text": "document txt write read note",
  "file-zip": "archive compress package bundle rar",
  "files": "documents multiple explorer browser",
  "filter": "funnel sort search refine narrow",
  "filter-filled": "funnel sort refine solid active",
  "flag": "mark report notice banner sign",
  "flame": "fire hot burn danger popular",
  "fold": "collapse hide compress close squeeze",
  "fold-down": "collapse hide bottom close minimize",
  "fold-up": "collapse hide top close minimize",
  "folder": "directory container storage organize",
  "folder-active": "directory current open selected working",
  "folder-library": "collection books archive storage group",
  "folder-opened": "directory container storage organize expanded",
  "forward": "next right advance go arrow",
  "game": "play controller joystick fun entertainment",
  "gear": "settings configuration preferences options setup",
  "gift": "present box reward package surprise",
  "gist": "github snippet code share note pr",
  "gist-fork": "copy branch split duplicate share code pr",
  "gist-private": "lock secret hidden secure code pr",
  "gist-secret": "lock hidden private secure code pr",
  "git-branch": "source control version tree fork",
  "git-branch-changes": "diff modify edit update version pr",
  "git-branch-conflicts": "error clash issue problem merge exclamation pr",
  "git-branch-staged-changes": "ready commit add prepare version pr",
  "git-commit": "save record version snapshot",
  "git-compare": "diff changes versus match check pr versions",
  "git-merge": "combine join integrate branch",
  "git-pull-request": "pr review merge contribution",
  "git-pull-request-closed": "pr done finish reject end",
  "git-pull-request-create": "pr new add start open",
  "git-pull-request-done": "pr merged complete success check completed",
  "git-pull-request-draft": "pr wip work pending edit",
  "git-pull-request-go-to-changes": "pr diff jump view files",
  "git-pull-request-new-changes": "pr update fresh recent notification",
  "git-stash": "save hide store temp shelf",
  "git-stash-apply": "restore pop use retrieve load",
  "git-stash-pop": "restore remove retrieve load apply",
  "github-action": "ci cd automation workflow pipeline",
  "github-alt": "logo brand cat octocat social alternative",
  "github-inverted": "logo brand cat octocat white",
  "github-project": "board kanban plan organize tasks",
  "globe": "world internet web international network",
  "go-to-editing-session": "jump switch work context restore",
  "go-to-search": "find jump query look magnify",
  "grabber": "drag move handle grip hold",
  "graph": "chart visualization data analytics statistics",
  "graph-left": "chart plot visualize data side aligned",
  "graph-line": "chart plot trend data statistics",
  "graph-scatter": "chart plot dots data distribution",
  "gripper": "drag move handle dots hold",
  "group-by-ref-type": "sort organize category class kind reference",
  "heart": "like favorite love bookmark",
  "heart-filled": "love like favorite solid prefer",
  "history": "time past log record clock",
  "home": "house main start dashboard page",
  "horizontal-rule": "line separator divider split hr",
  "hubot": "bot robot ai assistant chat",
  "inbox": "mail message tray receive incoming agent",
  "indent": "tab space move right format text",
  "index-zero": "start first number count search find",
  "info": "information help about details",
  "insert": "add new enter input plus item",
  "inspect": "check examine debug look analyze element",
  "issue-draft": "bug ticket wip pending unsaved",
  "issue-reopened": "bug ticket active again back",
  "issues": "bug problem task ticket github tasks",
  "italic": "text format style slant emphasis",
  "jersey": "shirt clothing team sport uniform",
  "json": "bracket data format code structure",
  "kebab-vertical": "menu more options dots overflow",
  "key": "password secret access security authentication",
  "keyboard-tab": "key indent space move jump nes next edit suggestion accept",
  "keyboard-tab-above": "key indent up move jump nes next edit suggestion accept",
  "keyboard-tab-below": "key indent down move jump nes next edit suggestion accept",
  "law": "legal license terms compliance",
  "layers": "stack sheets levels overlay group",
  "layers-active": "stack sheets current selected",
  "layers-dot": "stack sheets badge notification alert",
  "layout": "view arrange grid panel design",
  "layout-activitybar-left": "view sidebar menu dock west activity bar",
  "layout-activitybar-right": "view sidebar menu dock east activity bar",
  "layout-centered": "view middle focus align balance",
  "layout-menubar": "view top header options nav",
  "layout-panel": "view bottom terminal output dock",
  "layout-panel-center": "view bottom middle align dock",
  "layout-panel-dock": "view bottom fix anchor attach",
  "layout-panel-justify": "view bottom stretch fill align",
  "layout-panel-left": "view side west dock vertical",
  "layout-panel-off": "view hide close remove invisible",
  "layout-panel-right": "view side east dock vertical",
  "layout-sidebar-left": "view explorer tree west dock",
  "layout-sidebar-left-dock": "view explorer fix anchor west",
  "layout-sidebar-left-off": "view hide close remove explorer",
  "layout-sidebar-right": "view outline east dock secondary",
  "layout-sidebar-right-dock": "view outline fix anchor east",
  "layout-sidebar-right-off": "view hide close remove outline",
  "layout-statusbar": "view bottom footer info bar status",
  "library": "collection repository storage archive",
  "lightbulb": "idea suggestion tip hint smart",
  "lightbulb-autofix": "idea repair solve magic correct suggestion auto fix",
  "lightbulb-empty": "idea off hollow outline thought suggestion",
  "lightbulb-sparkle": "idea ai magic smart suggestion intelligent",
  "link": "url hyperlink connection chain reference",
  "link-external": "url open new outside",
  "list-filter": "sort refine search narrow view",
  "list-flat": "view plain simple linear rows",
  "list-ordered": "numbered sequence steps order",
  "list-selection": "choose pick check active highlight",
  "list-tree": "hierarchy structure nested branches view files folders directory project",
  "list-unordered": "bullet items points",
  "live-share": "collaborate remote pair connect together",
  "loading": "spinner progress wait processing busy",
  "location": "map place pin marker gps",
  "lock-small": "secure private mini tiny key readonly",
  "log-in": "sign in enter access auth arrow",
  "log-out": "sign out exit leave disconnect arrow",
  "logo-github": "brand cat octocat git social",
  "magnet": "stick snap attract pull hold",
  "mail": "email message envelope communication",
  "mail-read": "email open message seen envelope",
  "mail-reply": "email respond answer back arrow",
  "map": "location guide plan chart area",
  "map-filled": "location guide solid area place",
  "map-vertical": "location guide up down chart",
  "map-vertical-filled": "location guide solid up down",
  "markdown": "text format document md writing",
  "mcp": "protocol connect server client model ai tools context",
  "megaphone": "shout announce broadcast loud speaker notification",
  "mention": "at tag user notify address collaborate communication",
  "menu": "hamburger navigation options list",
  "merge": "combine join unite integrate",
  "merge-into": "combine join unite flow arrow pr git",
  "mic": "microphone audio voice record sound",
  "mic-filled": "audio voice record solid sound text speech tts microphone",
  "milestone": "goal target flag marker progress git project issue pr",
  "mirror": "reflect copy duplicate sync",
  "more": "ellipsis menu options actions dots",
  "mortar-board": "education learn school degree hat graduation",
  "move": "drag reorder relocate transfer",
  "multiple-windows": "screens views panels many stack",
  "music": "note sound audio song melody",
  "mute": "silent quiet off sound volume",
  "new-collection": "create add group set plus",
  "new-file": "create add document blank",
  "new-folder": "create add directory blank",
  "new-session": "create add compose edit chat start",
  "newline": "enter return break text arrow character",
  "no-newline": "stop end text break slash",
  "note": "document memo text write",
  "notebook": "jupyter code document interactive",
  "notebook-template": "jupyter pattern layout model file",
  "octoface": "github cat logo brand face octocat",
  "open-in-product": "launch external view app arrow",
  "open-in-window": "launch external view arrow new",
  "open-preview": "view see display show window",
  "organization": "company business group team",
  "output": "result console terminal log",
  "package": "box module library dependency",
  "paintcan": "color fill bucket art design paint can",
  "pass": "check success complete done approved",
  "pass-filled": "check success solid ok done",
  "percentage": "ratio math number rate",
  "person": "user account profile human contact",
  "person-add": "user invite new plus friend",
  "piano": "music keys instrument sound play",
  "pie-chart": "graph data visualize circle stats",
  "pin": "attach fix stick bookmark",
  "pinned": "fixed sticky attached saved marker item",
  "pinned-dirty": "fixed sticky unsaved modified dot item changes",
  "play": "run start execute begin",
  "play-circle": "run start round media",
  "plug": "extension connect addon power plugin",
  "preserve-case": "text search match caps font",
  "preview": "view see look display",
  "primitive-square": "shape box block stop solid",
  "project": "workspace folder solution repository",
  "pulse": "heartbeat activity monitor line health",
  "python": "language code snake logo dev",
  "question": "help info unknown ask",
  "quote": "text cite reference speech mark",
  "quotes": "text cite reference speech marks double",
  "radio-tower": "signal broadcast antenna wireless connect",
  "reactions": "emoji face emotion respond feeling",
  "record": "capture start save log",
  "record-keys": "macro type input save keyboard keystrokes",
  "record-small": "capture dot mini tiny circle",
  "redo": "repeat forward restore again action",
  "references": "links citations uses calls list code",
  "refresh": "reload update sync restart",
  "regex": "pattern search expression match regular",
  "remote": "server cloud ssh connection",
  "remote-explorer": "server cloud ssh view connect",
  "remove": "delete trash clear eliminate",
  "remove-small": "delete minus mini tiny trash",
  "rename": "edit change label title text",
  "replace": "swap substitute change exchange",
  "replace-all": "swap change bulk many substitute",
  "repo": "repository git source project",
  "repo-clone": "git copy download duplicate project repository",
  "repo-fetch": "git download update sync get repository",
  "repo-force-push": "git upload overwrite danger arrow repository",
  "repo-pinned": "git favorite saved fixed project repository",
  "repo-pull": "git download update sync arrow repository",
  "repo-push": "git upload send sync arrow repository",
  "repo-selected": "git active current check project repository",
  "repo-sync": "git refresh update cycle arrows repository",
  "report": "document analytics summary data",
  "request-changes": "pr review reject edit feedback",
  "robot": "ai bot automation machine android",
  "rocket": "launch deploy fast start",
  "root-folder": "directory base home start project",
  "root-folder-opened": "directory base home expanded project",
  "rss": "feed news subscribe broadcast wifi",
  "ruby": "language code gem jewel red",
  "run-above": "play execute up previous start",
  "run-all": "play execute everything batch start",
  "run-all-coverage": "test execute metrics everything report",
  "run-below": "play execute down next start",
  "run-coverage": "test execute metrics report check",
  "run-errors": "test fail bug issue problem",
  "run-with-deps": "play execute tree chain link dependencies",
  "save": "disk store keep preserve",
  "save-all": "disk store keep preserve bulk",
  "save-as": "disk store new copy file",
  "screen-cut": "scissors snip capture screenshot clip window select cutting",
  "screen-full": "view maximize expand monitor display",
  "screen-normal": "view restore window monitor display",
  "search": "find query look magnify locate",
  "search-fuzzy": "find approximate match loose query",
  "search-large": "find big magnify zoom query",
  "search-sparkle": "ai find magic smart query",
  "search-stop": "find cancel halt end query",
  "send": "mail message submit paper plane go",
  "send-to-remote-agent": "transmit upload cloud server go",
  "server": "host backend database remote",
  "server-environment": "host cloud settings config box",
  "server-process": "host run execute task gear",
  "session-in-progress": "working busy active clock wait",
  "settings": "gear configuration preferences options",
  "settings-gear": "configuration preferences options setup",
  "share": "export send link collaborate arrow",
  "shield": "security protect safety guard protection",
  "skip": "next jump pass ignore arrow",
  "smiley": "face happy emotion good smile",
  "snake": "python reptile game animal curve",
  "sort-precedence": "order rank priority list arrange by",
  "source-control": "git version scm branch",
  "sparkle": "ai magic auto smart copilot automated feature",
  "sparkle-filled": "ai magic solid star shine",
  "split-horizontal": "divide layout pane window horizontally",
  "split-vertical": "divide layout pane window vertically",
  "squirrel": "animal ship release deploy mascot",
  "star": "favorite bookmark rating highlight",
  "star-full": "favorite solid rate best bookmark",
  "star-half": "favorite partial rate middle bookmark",
  "stop-circle": "halt end cancel round",
  "strikethrough": "text format delete cross line",
  "surround-with": "wrap enclose code brackets container",
  "symbol-boolean": "code true false logic type",
  "symbol-class": "code object type definition",
  "symbol-color": "code paint palette type style",
  "symbol-constant": "code fixed value type immutable",
  "symbol-enum": "code list options type set",
  "symbol-enum-member": "code item option value part",
  "symbol-field": "code property variable data member",
  "symbol-file": "code document script source type",
  "symbol-interface": "code contract api type definition",
  "symbol-key": "code id access property name",
  "symbol-keyword": "code reserved syntax language term",
  "symbol-method": "code function procedure definition",
  "symbol-method-arrow": "code function call action run",
  "symbol-misc": "code other various general item miscellaneous",
  "symbol-module": "code package library container import",
  "symbol-numeric": "code number digit math count",
  "symbol-operator": "code math logic calc function",
  "symbol-parameter": "code input argument variable value",
  "symbol-property": "code attribute field value data",
  "symbol-reference": "code link pointer alias use",
  "symbol-ruler": "code measure size scale unit",
  "symbol-snippet": "code template fragment reuse paste",
  "symbol-string": "code text chars word value",
  "symbol-structure": "code object data model shape",
  "sync-ignored": "refresh skip exclude update circle",
  "table": "grid data rows columns sheet",
  "tag": "label mark version release",
  "target": "aim goal bullseye focus point",
  "tasklist": "todo check items plan manage task list",
  "telescope": "search find explore look space",
  "terminal": "console command shell cli",
  "terminal-bash": "console shell script linux command",
  "terminal-cmd": "console shell windows command prompt",
  "terminal-debian": "console shell linux os logo",
  "terminal-git-bash": "console shell command logo",
  "terminal-linux": "console shell os penguin logo",
  "terminal-powershell": "console shell windows script logo",
  "terminal-tmux": "console multiplexer split window tool",
  "terminal-ubuntu": "console shell linux os logo",
  "text-size": "font typography scale zoom",
  "thinking": "ai brain process wait loading",
  "three-bars": "menu hamburger list options nav",
  "thumbsdown": "dislike bad no reject vote thumbs down",
  "thumbsdown-filled": "dislike bad no reject solid thumbs down",
  "thumbsup": "like good yes approve vote thumbs up",
  "thumbsup-filled": "like good yes approve solid thumbs up",
  "tools": "settings config repair fix utils",
  "trash": "delete remove bin discard",
  "triangle-down": "arrow direction point shape descend pointing",
  "triangle-left": "arrow direction point shape back pointing",
  "triangle-right": "arrow direction point shape forward pointing",
  "triangle-up": "arrow direction point shape ascend pointing",
  "twitter": "social bird logo brand share",
  "type-hierarchy": "structure class tree inherit view",
  "type-hierarchy-sub": "structure child down inherit view",
  "type-hierarchy-super": "structure parent up inherit view",
  "unarchive": "restore open unpack box retrieve",
  "unfold": "expand show open reveal spread",
  "ungroup-by-ref-type": "sort list flat view mix reference",
  "unlock": "open unsecure access unlocked",
  "unmute": "sound volume audio hear",
  "unverified": "check hollow pending wait circle",
  "variable": "code value store data box",
  "variable-group": "code collection set list data",
  "verified": "check approved trusted confirmed",
  "verified-filled": "check solid approved trusted ok",
  "versions": "history changes git time backup",
  "vm": "computer server remote machine box virtual",
  "vm-active": "computer running working remote virtual machine",
  "vm-connect": "computer link remote ssh join",
  "vm-outline": "computer box shape remote machine",
  "vm-running": "computer play active remote",
  "vm-small": "computer mini tiny remote box",
  "vr": "virtual reality glasses headset 3d",
  "vscode": "editor logo brand microsoft code vs",
  "vscode-insiders": "editor logo brand green beta vs code",
  "wand": "magic fix auto spell wizard",
  "watch": "monitor observe track follow",
  "whitespace": "space invisible char format view character",
  "whole-word": "search match text complete exact",
  "window": "application frame panel view",
  "window-active": "view current focus selected frame",
  "word-wrap": "text format line break view",
  "workspace-trusted": "safe verified secure approved",
  "workspace-unknown": "status question unsure check folder trust",
  "workspace-untrusted": "status danger warning shield folder exclamation",
  "zap": "flash electric power energy fast",
  "zoom-in": "magnify enlarge increase expand",
  "zoom-out": "reduce shrink decrease minimize",
};
