// AUTO-GENERATED icon search keywords (part 1 of 2), from @vscode/codicons
// metadata (tags + description). Do NOT edit by hand. These are search-match aids
// only — matched as the user types, never shown as translated prose, so they live
// here rather than in the l10n catalog. Split into two parts purely to keep each
// file under the line cap; iconKeywords.ts merges them back into ICON_KEYWORDS.
export const ICON_KEYWORDS_PART_1: Record<string, string> = {
  "account": "person people face user contact profile avatar",
  "activate-breakpoints": "debug dot circle toggle switch enable",
  "add": "plus new create combine more insert item",
  "add-small": "plus new create mini tiny",
  "agent": "ai bot assistant robot service",
  "alert": "warning error danger notification triangle exclamation",
  "archive": "save box delivery package store compress items",
  "array": "list collection brackets data structure",
  "arrow-both": "switch swap exchange bidirectional transfer",
  "arrow-circle-down": "download direction navigate round circular pointing",
  "arrow-circle-left": "back direction navigate round previous circular pointing",
  "arrow-circle-right": "forward direction navigate round next circular pointing",
  "arrow-circle-up": "upload direction navigate round circular pointing",
  "arrow-down": "direction navigate sort download descend pointing",
  "arrow-left": "direction navigate back previous pointing",
  "arrow-right": "direction navigate forward next pointing",
  "arrow-small-down": "direction navigate mini tiny descend pointing",
  "arrow-small-left": "direction navigate back mini tiny pointing",
  "arrow-small-right": "direction navigate forward mini tiny pointing",
  "arrow-small-up": "direction navigate mini tiny ascend pointing",
  "arrow-swap": "switch exchange replace direction arrows",
  "arrow-up": "direction navigate sort upload ascend pointing",
  "ask": "question help chat inquiry support message bubble mark",
  "attach": "clip paperclip file link connect add item",
  "azure": "cloud microsoft service platform logo",
  "azure-devops": "cloud microsoft service cicd logo",
  "beaker": "test lab tube science experiment flask testing experimental feature",
  "beaker-stop": "test experiment halt cancel lab",
  "bell": "alert notify notification alarm reminder",
  "bell-dot": "alert notify notification alarm unread badge",
  "bell-slash": "mute silent quiet no-notification off notifications disabled",
  "bell-slash-dot": "mute silent quiet unread badge notifications disabled",
  "blank": "empty nothing void clear space",
  "bold": "text format weight font style strong formatting",
  "book": "library text read documentation manual guide reading material",
  "bookmark": "save mark favorite remember flag later",
  "bracket-dot": "code json array badge",
  "bracket-error": "code json array issue problem",
  "briefcase": "work workplace business professional job related",
  "broadcast": "tower signal connect connection transmit wireless",
  "browser": "web internet page window site webpage",
  "bug": "error issue insect problem defect",
  "build": "compile make construct tools hammer",
  "calendar": "day time week month date schedule event planner",
  "call-incoming": "phone voice connection receive",
  "call-outgoing": "phone voice connection send",
  "case-sensitive": "search filter option letters words text",
  "chat-sparkle": "ai copilot message magic suggestion",
  "chat-sparkle-error": "ai copilot message issue problem",
  "chat-sparkle-warning": "ai copilot message alert caution exclamation",
  "check": "checkmark select checked mark complete finish done accept approve success",
  "check-all": "checkmark select everything checked mark complete finish done accept approve bulk",
  "checklist": "checkmark select checked mark complete finish done todo task list",
  "chevron-down": "twistie tree node folder fold collapse expand dropdown pointing",
  "chevron-left": "twistie tree node folder fold collapse back pointing",
  "chevron-right": "twistie tree node folder fold expand forward pointing",
  "chevron-up": "twistie tree node folder fold collapse expand pointing",
  "chip": "hardware processor cpu gpu silicon integrated computer",
  "chrome-close": "menu bar window dismiss exit quit",
  "chrome-maximize": "menu bar window large increase expand",
  "chrome-minimize": "menu bar window small decrease reduce",
  "chrome-restore": "menu bar window resize normal",
  "circle-filled": "dot round small bullet point breakpoint",
  "circle-large": "dot round bullet point outline",
  "circle-large-filled": "dot round bullet point",
  "circle-outline": "round shape empty ring hollow",
  "circle-slash": "error block stop disable prohibited forbidden blocked disabled",
  "circle-small": "dot point round tiny mini outline",
  "circle-small-filled": "dot point round tiny mini solid",
  "circuit-board": "iot device process hardware technology",
  "clear-all": "reset remove delete clean empty",
  "clippy": "clipboard document edit copy paste",
  "clockface": "time watch schedule history wait hour minute clock face showing",
  "clone": "copy duplicate replicate git repo",
  "close": "remove delete cancel stop dismiss exit",
  "close-all": "remove bulk dismiss exit items",
  "cloud": "online service storage sync remote",
  "cloud-download": "install import retrieve fetch from",
  "cloud-small": "online storage mini tiny remote",
  "cloud-upload": "export save send publish",
  "code": "embed script programming development source",
  "code-oss": "vscode open source editor logo brand",
  "code-review": "pr pull request check inspect examine",
  "coffee": "break drink beverage java pause time",
  "collapse-all": "bulk fold minimize hide tree items",
  "collection": "group set library stack gather items",
  "collection-small": "group set library mini tiny",
  "color-mode": "switch dark light contrast theme toggle",
  "combine": "merge join unite mix blend items",
  "comment": "dialog message bubble chat feedback note",
  "comment-discussion": "dialog message bubble chat conversation feedback",
  "comment-discussion-quote": "chat reply reference cite message quoted",
  "comment-discussion-sparkle": "ai chat copilot magic suggestion intelligent",
  "comment-draft": "message unsaved pending write edit pr",
  "comment-unresolved": "message open pending issue active pr",
  "compass": "navigate direction orient guide map navigation",
  "compass-active": "navigate direction orient guide",
  "compass-dot": "navigate direction orient badge notification",
  "copilot": "ai assistant help automation suggestion",
  "copilot-blocked": "ai stop prevent ban restricted intelligent agent",
  "copilot-error": "ai issue problem fail bug cross intelligent agent",
  "copilot-in-progress": "ai loading thinking working busy spinner waiting intelligent agent",
  "copilot-large": "ai assistant big logo brand intelligent agent",
  "copilot-not-connected": "ai offline disconnected network link intelligent agent",
  "copilot-snooze": "ai sleep pause wait later intelligent agent snoozed",
  "copilot-success": "ai check done complete ok intelligent agent tick pass",
  "copilot-unavailable": "ai offline missing gone disabled intelligent agent",
  "copilot-warning": "ai alert caution attention issue exclamation intelligent agent",
  "copilot-warning-large": "ai alert caution big attention exclamation intelligent agent",
  "copy": "duplicate clone clipboard paste content",
  "coverage": "test percent code quality metrics",
  "credit-card": "payment merchant money billing purchase",
  "cursor": "pointer mouse click select arrow",
  "dash": "line minus subtract hyphen separator",
  "dashboard": "panel stats dial overview metrics",
  "database": "sql storage data server table",
  "debug": "run test troubleshoot fix breakpoint",
  "debug-all": "run test everything suite batch play",
  "debug-alt": "run execute play start alternative",
  "debug-alt-small": "run play mini tiny start execute",
  "debug-breakpoint-conditional": "stop pause if logic test",
  "debug-breakpoint-conditional-unverified": "stop pause if grey inactive",
  "debug-breakpoint-data": "stop pause variable value watch",
  "debug-breakpoint-data-unverified": "stop pause variable grey inactive",
  "debug-breakpoint-function": "stop pause method call triangle",
  "debug-breakpoint-function-unverified": "stop pause method grey inactive",
  "debug-breakpoint-log": "print message console diamond record logpoint",
  "debug-breakpoint-log-unverified": "print message grey inactive diamond logpoint",
  "debug-breakpoint-unsupported": "stop error invalid broken fail exclamation",
  "debug-connected": "attach link online active plug debugger",
  "debug-console": "terminal command input compile build output",
  "debug-continue": "play resume next forward run debugging",
  "debug-continue-small": "play resume mini tiny run",
  "debug-coverage": "test percent metrics quality report",
  "debug-disconnect": "stop unplug detach offline end debugger",
  "debug-line-by-line": "step walk trace flow execute",
  "debug-pause": "break halt wait freeze stop debugging",
  "debug-rerun": "restart again repeat loop reload session",
  "debug-restart": "reload reset again cycle refresh debugging",
  "debug-restart-frame": "stack reset up back context",
  "debug-reverse-continue": "back rewind previous undo return",
  "debug-stackframe": "call layer context memory trace stack frame",
  "debug-stackframe-active": "call layer current now focus stack frame",
  "debug-start": "run play launch begin execute debugging",
  "debug-step-back": "reverse previous undo return rewind arrow",
  "debug-step-into": "enter down inside drill call arrow",
  "debug-step-out": "exit up return leave escape",
  "debug-step-over": "next skip jump forward pass",
  "debug-stop": "terminate end kill halt finish exit square debugging",
  "device-camera": "capture picture image photo screenshot",
  "device-camera-video": "movie record capture film",
  "device-mobile": "phone handheld smartphone responsive",
  "diff": "compare changes difference git version comparison",
  "diff-added": "git change new insert green changes",
  "diff-ignored": "git change skip excluded changes",
  "diff-modified": "git change edit updated yellow changes",
  "diff-multiple": "compare changes files batch many git pr diffs",
  "diff-removed": "git change delete red changes",
  "diff-renamed": "git change move changes",
  "diff-single": "compare change file one individual git pr",
  "discard": "undo revert throw trash cancel delete changes",
  "download": "get retrieve save install pull cloud",
  "edit": "pencil modify write change update",
  "edit-code": "write modify script program change",
  "edit-session": "work context state save restore",
  "edit-sparkle": "ai magic auto fix refactor smart intelligent",
  "editor-layout": "split grid view arrange window",
  "empty-window": "blank new clear frame start",
  "eraser": "delete remove clear rub clean",
  "error": "stop problem issue alert warning critical",
  "error-small": "issue problem bug mini tiny cross",
  "exclude": "remove hide filter minus ban item",
  "expand-all": "open show unfold reveal tree items",
  "export": "save send out download extract data",
  "extensions": "plugin addon package module marketplace plugins",
  "extensions-large": "plugins addons marketplace big",
  "eye": "view watch see visibility preview",
  "eye-closed": "hide hidden invisible privacy conceal",
  "feedback": "comment review opinion rate message",
  "file": "document text page content",
  "file-binary": "data raw executable blob 01",
  "file-code": "source programming script development",
  "file-media": "image video audio picture movie",
  "file-pdf": "document adobe print read paper",
  "file-submodule": "git repo link reference external",
  "file-symlink-directory": "link shortcut alias folder pointer",
  "file-symlink-file": "link shortcut alias document pointer",
  "file-text": "document txt write read note",
  "file-zip": "archive compress package bundle rar",
  "files": "documents multiple explorer browser",
  "filter": "funnel sort search refine narrow",
  "filter-filled": "funnel sort refine solid active",
  "flag": "mark report notice banner sign",
  "flame": "fire hot burn danger popular",
  "fold": "collapse hide compress close squeeze",
  "fold-down": "collapse hide bottom close minimize",
  "fold-up": "collapse hide top close minimize",
  "folder": "directory container storage organize",
  "folder-active": "directory current open selected working",
  "folder-library": "collection books archive storage group",
  "folder-opened": "directory container storage organize expanded",
  "forward": "next right advance go arrow",
  "game": "play controller joystick fun entertainment",
  "gear": "settings configuration preferences options setup",
  "gift": "present box reward package surprise",
  "gist": "github snippet code share note pr",
  "gist-fork": "copy branch split duplicate share code pr",
  "gist-private": "lock secret hidden secure code pr",
  "gist-secret": "lock hidden private secure code pr",
  "git-branch": "source control version tree fork",
  "git-branch-changes": "diff modify edit update version pr",
  "git-branch-conflicts": "error clash issue problem merge exclamation pr",
  "git-branch-staged-changes": "ready commit add prepare version pr",
  "git-commit": "save record version snapshot",
  "git-compare": "diff changes versus match check pr versions",
  "git-merge": "combine join integrate branch",
  "git-pull-request": "pr review merge contribution",
  "git-pull-request-closed": "pr done finish reject end",
  "git-pull-request-create": "pr new add start open",
  "git-pull-request-done": "pr merged complete success check completed",
  "git-pull-request-draft": "pr wip work pending edit",
  "git-pull-request-go-to-changes": "pr diff jump view files",
  "git-pull-request-new-changes": "pr update fresh recent notification",
  "git-stash": "save hide store temp shelf",
  "git-stash-apply": "restore pop use retrieve load",
  "git-stash-pop": "restore remove retrieve load apply",
  "github-action": "ci cd automation workflow pipeline",
  "github-alt": "logo brand cat octocat social alternative",
  "github-inverted": "logo brand cat octocat white",
  "github-project": "board kanban plan organize tasks",
  "globe": "world internet web international network",
  "go-to-editing-session": "jump switch work context restore",
  "go-to-search": "find jump query look magnify",
  "grabber": "drag move handle grip hold",
  "graph": "chart visualization data analytics statistics",
  "graph-left": "chart plot visualize data side aligned",
  "graph-line": "chart plot trend data statistics",
  "graph-scatter": "chart plot dots data distribution",
  "gripper": "drag move handle dots hold",
  "group-by-ref-type": "sort organize category class kind reference",
  "heart": "like favorite love bookmark",
  "heart-filled": "love like favorite solid prefer",
  "history": "time past log record clock",
  "home": "house main start dashboard page",
  "horizontal-rule": "line separator divider split hr",
  "hubot": "bot robot ai assistant chat",
  "inbox": "mail message tray receive incoming agent",
  "indent": "tab space move right format text",
  "index-zero": "start first number count search find",
  "info": "information help about details",
  "insert": "add new enter input plus item",
  "inspect": "check examine debug look analyze element",
  "issue-draft": "bug ticket wip pending unsaved",
  "issue-reopened": "bug ticket active again back",
  "issues": "bug problem task ticket github tasks",
  "italic": "text format style slant emphasis",
  "jersey": "shirt clothing team sport uniform",
  "json": "bracket data format code structure",
  "kebab-vertical": "menu more options dots overflow",
  "key": "password secret access security authentication",
  "keyboard-tab": "key indent space move jump nes next edit suggestion accept",
  "keyboard-tab-above": "key indent up move jump nes next edit suggestion accept",
  "keyboard-tab-below": "key indent down move jump nes next edit suggestion accept",
  "law": "legal license terms compliance",
  "layers": "stack sheets levels overlay group",
  "layers-active": "stack sheets current selected",
  "layers-dot": "stack sheets badge notification alert",
  "layout": "view arrange grid panel design",
};
