// AUTO-GENERATED icon search keywords (part 2 of 2), from @vscode/codicons
// metadata (tags + description). Do NOT edit by hand. These are search-match aids
// only — matched as the user types, never shown as translated prose, so they live
// here rather than in the l10n catalog. Split into two parts purely to keep each
// file under the line cap; iconKeywords.ts merges them back into ICON_KEYWORDS.
export const ICON_KEYWORDS_PART_2: Record<string, string> = {
  "layout-activitybar-left": "view sidebar menu dock west activity bar",
  "layout-activitybar-right": "view sidebar menu dock east activity bar",
  "layout-centered": "view middle focus align balance",
  "layout-menubar": "view top header options nav",
  "layout-panel": "view bottom terminal output dock",
  "layout-panel-center": "view bottom middle align dock",
  "layout-panel-dock": "view bottom fix anchor attach",
  "layout-panel-justify": "view bottom stretch fill align",
  "layout-panel-left": "view side west dock vertical",
  "layout-panel-off": "view hide close remove invisible",
  "layout-panel-right": "view side east dock vertical",
  "layout-sidebar-left": "view explorer tree west dock",
  "layout-sidebar-left-dock": "view explorer fix anchor west",
  "layout-sidebar-left-off": "view hide close remove explorer",
  "layout-sidebar-right": "view outline east dock secondary",
  "layout-sidebar-right-dock": "view outline fix anchor east",
  "layout-sidebar-right-off": "view hide close remove outline",
  "layout-statusbar": "view bottom footer info bar status",
  "library": "collection repository storage archive",
  "lightbulb": "idea suggestion tip hint smart",
  "lightbulb-autofix": "idea repair solve magic correct suggestion auto fix",
  "lightbulb-empty": "idea off hollow outline thought suggestion",
  "lightbulb-sparkle": "idea ai magic smart suggestion intelligent",
  "link": "url hyperlink connection chain reference",
  "link-external": "url open new outside",
  "list-filter": "sort refine search narrow view",
  "list-flat": "view plain simple linear rows",
  "list-ordered": "numbered sequence steps order",
  "list-selection": "choose pick check active highlight",
  "list-tree": "hierarchy structure nested branches view files folders directory project",
  "list-unordered": "bullet items points",
  "live-share": "collaborate remote pair connect together",
  "loading": "spinner progress wait processing busy",
  "location": "map place pin marker gps",
  "lock-small": "secure private mini tiny key readonly",
  "log-in": "sign in enter access auth arrow",
  "log-out": "sign out exit leave disconnect arrow",
  "logo-github": "brand cat octocat git social",
  "magnet": "stick snap attract pull hold",
  "mail": "email message envelope communication",
  "mail-read": "email open message seen envelope",
  "mail-reply": "email respond answer back arrow",
  "map": "location guide plan chart area",
  "map-filled": "location guide solid area place",
  "map-vertical": "location guide up down chart",
  "map-vertical-filled": "location guide solid up down",
  "markdown": "text format document md writing",
  "mcp": "protocol connect server client model ai tools context",
  "megaphone": "shout announce broadcast loud speaker notification",
  "mention": "at tag user notify address collaborate communication",
  "menu": "hamburger navigation options list",
  "merge": "combine join unite integrate",
  "merge-into": "combine join unite flow arrow pr git",
  "mic": "microphone audio voice record sound",
  "mic-filled": "audio voice record solid sound text speech tts microphone",
  "milestone": "goal target flag marker progress git project issue pr",
  "mirror": "reflect copy duplicate sync",
  "more": "ellipsis menu options actions dots",
  "mortar-board": "education learn school degree hat graduation",
  "move": "drag reorder relocate transfer",
  "multiple-windows": "screens views panels many stack",
  "music": "note sound audio song melody",
  "mute": "silent quiet off sound volume",
  "new-collection": "create add group set plus",
  "new-file": "create add document blank",
  "new-folder": "create add directory blank",
  "new-session": "create add compose edit chat start",
  "newline": "enter return break text arrow character",
  "no-newline": "stop end text break slash",
  "note": "document memo text write",
  "notebook": "jupyter code document interactive",
  "notebook-template": "jupyter pattern layout model file",
  "octoface": "github cat logo brand face octocat",
  "open-in-product": "launch external view app arrow",
  "open-in-window": "launch external view arrow new",
  "open-preview": "view see display show window",
  "organization": "company business group team",
  "output": "result console terminal log",
  "package": "box module library dependency",
  "paintcan": "color fill bucket art design paint can",
  "pass": "check success complete done approved",
  "pass-filled": "check success solid ok done",
  "percentage": "ratio math number rate",
  "person": "user account profile human contact",
  "person-add": "user invite new plus friend",
  "piano": "music keys instrument sound play",
  "pie-chart": "graph data visualize circle stats",
  "pin": "attach fix stick bookmark",
  "pinned": "fixed sticky attached saved marker item",
  "pinned-dirty": "fixed sticky unsaved modified dot item changes",
  "play": "run start execute begin",
  "play-circle": "run start round media",
  "plug": "extension connect addon power plugin",
  "preserve-case": "text search match caps font",
  "preview": "view see look display",
  "primitive-square": "shape box block stop solid",
  "project": "workspace folder solution repository",
  "pulse": "heartbeat activity monitor line health",
  "python": "language code snake logo dev",
  "question": "help info unknown ask",
  "quote": "text cite reference speech mark",
  "quotes": "text cite reference speech marks double",
  "radio-tower": "signal broadcast antenna wireless connect",
  "reactions": "emoji face emotion respond feeling",
  "record": "capture start save log",
  "record-keys": "macro type input save keyboard keystrokes",
  "record-small": "capture dot mini tiny circle",
  "redo": "repeat forward restore again action",
  "references": "links citations uses calls list code",
  "refresh": "reload update sync restart",
  "regex": "pattern search expression match regular",
  "remote": "server cloud ssh connection",
  "remote-explorer": "server cloud ssh view connect",
  "remove": "delete trash clear eliminate",
  "remove-small": "delete minus mini tiny trash",
  "rename": "edit change label title text",
  "replace": "swap substitute change exchange",
  "replace-all": "swap change bulk many substitute",
  "repo": "repository git source project",
  "repo-clone": "git copy download duplicate project repository",
  "repo-fetch": "git download update sync get repository",
  "repo-force-push": "git upload overwrite danger arrow repository",
  "repo-pinned": "git favorite saved fixed project repository",
  "repo-pull": "git download update sync arrow repository",
  "repo-push": "git upload send sync arrow repository",
  "repo-selected": "git active current check project repository",
  "repo-sync": "git refresh update cycle arrows repository",
  "report": "document analytics summary data",
  "request-changes": "pr review reject edit feedback",
  "robot": "ai bot automation machine android",
  "rocket": "launch deploy fast start",
  "root-folder": "directory base home start project",
  "root-folder-opened": "directory base home expanded project",
  "rss": "feed news subscribe broadcast wifi",
  "ruby": "language code gem jewel red",
  "run-above": "play execute up previous start",
  "run-all": "play execute everything batch start",
  "run-all-coverage": "test execute metrics everything report",
  "run-below": "play execute down next start",
  "run-coverage": "test execute metrics report check",
  "run-errors": "test fail bug issue problem",
  "run-with-deps": "play execute tree chain link dependencies",
  "save": "disk store keep preserve",
  "save-all": "disk store keep preserve bulk",
  "save-as": "disk store new copy file",
  "screen-cut": "scissors snip capture screenshot clip window select cutting",
  "screen-full": "view maximize expand monitor display",
  "screen-normal": "view restore window monitor display",
  "search": "find query look magnify locate",
  "search-fuzzy": "find approximate match loose query",
  "search-large": "find big magnify zoom query",
  "search-sparkle": "ai find magic smart query",
  "search-stop": "find cancel halt end query",
  "send": "mail message submit paper plane go",
  "send-to-remote-agent": "transmit upload cloud server go",
  "server": "host backend database remote",
  "server-environment": "host cloud settings config box",
  "server-process": "host run execute task gear",
  "session-in-progress": "working busy active clock wait",
  "settings": "gear configuration preferences options",
  "settings-gear": "configuration preferences options setup",
  "share": "export send link collaborate arrow",
  "shield": "security protect safety guard protection",
  "skip": "next jump pass ignore arrow",
  "smiley": "face happy emotion good smile",
  "snake": "python reptile game animal curve",
  "sort-precedence": "order rank priority list arrange by",
  "source-control": "git version scm branch",
  "sparkle": "ai magic auto smart copilot automated feature",
  "sparkle-filled": "ai magic solid star shine",
  "split-horizontal": "divide layout pane window horizontally",
  "split-vertical": "divide layout pane window vertically",
  "squirrel": "animal ship release deploy mascot",
  "star": "favorite bookmark rating highlight",
  "star-full": "favorite solid rate best bookmark",
  "star-half": "favorite partial rate middle bookmark",
  "stop-circle": "halt end cancel round",
  "strikethrough": "text format delete cross line",
  "surround-with": "wrap enclose code brackets container",
  "symbol-boolean": "code true false logic type",
  "symbol-class": "code object type definition",
  "symbol-color": "code paint palette type style",
  "symbol-constant": "code fixed value type immutable",
  "symbol-enum": "code list options type set",
  "symbol-enum-member": "code item option value part",
  "symbol-field": "code property variable data member",
  "symbol-file": "code document script source type",
  "symbol-interface": "code contract api type definition",
  "symbol-key": "code id access property name",
  "symbol-keyword": "code reserved syntax language term",
  "symbol-method": "code function procedure definition",
  "symbol-method-arrow": "code function call action run",
  "symbol-misc": "code other various general item miscellaneous",
  "symbol-module": "code package library container import",
  "symbol-numeric": "code number digit math count",
  "symbol-operator": "code math logic calc function",
  "symbol-parameter": "code input argument variable value",
  "symbol-property": "code attribute field value data",
  "symbol-reference": "code link pointer alias use",
  "symbol-ruler": "code measure size scale unit",
  "symbol-snippet": "code template fragment reuse paste",
  "symbol-string": "code text chars word value",
  "symbol-structure": "code object data model shape",
  "sync-ignored": "refresh skip exclude update circle",
  "table": "grid data rows columns sheet",
  "tag": "label mark version release",
  "target": "aim goal bullseye focus point",
  "tasklist": "todo check items plan manage task list",
  "telescope": "search find explore look space",
  "terminal": "console command shell cli",
  "terminal-bash": "console shell script linux command",
  "terminal-cmd": "console shell windows command prompt",
  "terminal-debian": "console shell linux os logo",
  "terminal-git-bash": "console shell command logo",
  "terminal-linux": "console shell os penguin logo",
  "terminal-powershell": "console shell windows script logo",
  "terminal-tmux": "console multiplexer split window tool",
  "terminal-ubuntu": "console shell linux os logo",
  "text-size": "font typography scale zoom",
  "thinking": "ai brain process wait loading",
  "three-bars": "menu hamburger list options nav",
  "thumbsdown": "dislike bad no reject vote thumbs down",
  "thumbsdown-filled": "dislike bad no reject solid thumbs down",
  "thumbsup": "like good yes approve vote thumbs up",
  "thumbsup-filled": "like good yes approve solid thumbs up",
  "tools": "settings config repair fix utils",
  "trash": "delete remove bin discard",
  "triangle-down": "arrow direction point shape descend pointing",
  "triangle-left": "arrow direction point shape back pointing",
  "triangle-right": "arrow direction point shape forward pointing",
  "triangle-up": "arrow direction point shape ascend pointing",
  "twitter": "social bird logo brand share",
  "type-hierarchy": "structure class tree inherit view",
  "type-hierarchy-sub": "structure child down inherit view",
  "type-hierarchy-super": "structure parent up inherit view",
  "unarchive": "restore open unpack box retrieve",
  "unfold": "expand show open reveal spread",
  "ungroup-by-ref-type": "sort list flat view mix reference",
  "unlock": "open unsecure access unlocked",
  "unmute": "sound volume audio hear",
  "unverified": "check hollow pending wait circle",
  "variable": "code value store data box",
  "variable-group": "code collection set list data",
  "verified": "check approved trusted confirmed",
  "verified-filled": "check solid approved trusted ok",
  "versions": "history changes git time backup",
  "vm": "computer server remote machine box virtual",
  "vm-active": "computer running working remote virtual machine",
  "vm-connect": "computer link remote ssh join",
  "vm-outline": "computer box shape remote machine",
  "vm-running": "computer play active remote",
  "vm-small": "computer mini tiny remote box",
  "vr": "virtual reality glasses headset 3d",
  "vscode": "editor logo brand microsoft code vs",
  "vscode-insiders": "editor logo brand green beta vs code",
  "wand": "magic fix auto spell wizard",
  "watch": "monitor observe track follow",
  "whitespace": "space invisible char format view character",
  "whole-word": "search match text complete exact",
  "window": "application frame panel view",
  "window-active": "view current focus selected frame",
  "word-wrap": "text format line break view",
  "workspace-trusted": "safe verified secure approved",
  "workspace-unknown": "status question unsure check folder trust",
  "workspace-untrusted": "status danger warning shield folder exclamation",
  "zap": "flash electric power energy fast",
  "zoom-in": "magnify enlarge increase expand",
  "zoom-out": "reduce shrink decrease minimize",
};
