import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { renderBriefExportHtml, renderBriefMarkdown } from "../views/brief/briefExport";
import type { RoutineBrief } from "../exec/routineRunner";

function makeBrief(overrides?: Partial<RoutineBrief>): RoutineBrief {
  return {
    routineName: "Morning",
    generatedAt: "2026-08-06T07:30:00.000Z",
    verdict: "clear",
    attentionCount: 0,
    members: [
      { label: "Stats", status: "ok", headline: "5,000 lines", attention: false, durationMs: 120 },
      { label: "Standup", status: "ok", headline: "3 commits", attention: false, durationMs: 300 },
    ],
    summaryPath: "/reports/summary.md",
    ...overrides,
  };
}

const strings: Record<string, string> = {
  title: "Saropa Morning Brief",
  allClear: "All clear",
  needsAttention: "Needs attention ({count})",
  openReport: "Open report",
  openSummary: "Open full summary",
  saveHtml: "Save as HTML",
  copyMarkdown: "Copy as Markdown",
  openInBrowser: "Open in browser",
  exportFooter: "Generated by Saropa Workspace",
  none: "No routine has run this session.",
};

describe("renderBriefExportHtml", () => {
  test("produces a self-contained HTML document with title and routine name", () => {
    const html = renderBriefExportHtml(makeBrief(), strings);
    assert.ok(html.includes("<!DOCTYPE html>"));
    assert.ok(html.includes("<title>Saropa Morning Brief — Morning</title>"));
  });

  test("renders clear verdict with the allClear string", () => {
    const html = renderBriefExportHtml(makeBrief(), strings);
    assert.ok(html.includes("All clear"));
    assert.ok(html.includes('class="verdict clear"'));
  });

  test("renders attention verdict with count", () => {
    const brief = makeBrief({
      verdict: "attention",
      attentionCount: 2,
      members: [
        { label: "Deps", status: "failed", attention: true },
        { label: "Stats", status: "ok", headline: "ok", attention: false },
      ],
    });
    const html = renderBriefExportHtml(brief, strings);
    assert.ok(html.includes("Needs attention (2)"));
    assert.ok(html.includes('class="verdict attention"'));
  });

  test("renders member cards with labels and headlines", () => {
    const html = renderBriefExportHtml(makeBrief(), strings);
    assert.ok(html.includes("Stats"));
    assert.ok(html.includes("5,000 lines"));
    assert.ok(html.includes("Standup"));
    assert.ok(html.includes("3 commits"));
  });

  test("renders duration for members that have it", () => {
    const html = renderBriefExportHtml(makeBrief(), strings);
    assert.ok(html.includes("120 ms"));
    assert.ok(html.includes("300 ms"));
  });

  test("escapes HTML in member labels", () => {
    const brief = makeBrief({
      members: [{ label: "<script>alert(1)</script>", status: "ok", attention: false }],
    });
    const html = renderBriefExportHtml(brief, strings);
    assert.ok(!html.includes("<script>alert(1)</script>"));
    assert.ok(html.includes("&lt;script&gt;"));
  });

  test("includes the exportFooter string", () => {
    const html = renderBriefExportHtml(makeBrief(), strings);
    assert.ok(html.includes("Generated by Saropa Workspace"));
  });

  test("includes dark mode styles", () => {
    const html = renderBriefExportHtml(makeBrief(), strings);
    assert.ok(html.includes("prefers-color-scheme: dark"));
  });
});

describe("renderBriefMarkdown", () => {
  test("includes title, routine name, and verdict", () => {
    const md = renderBriefMarkdown(makeBrief(), strings);
    assert.ok(md.includes("**Saropa Morning Brief** — Morning"));
    assert.ok(md.includes("**All clear**"));
  });

  test("lists members with status emoji and headlines", () => {
    const md = renderBriefMarkdown(makeBrief(), strings);
    assert.ok(md.includes("✅ **Stats** — 5,000 lines"));
    assert.ok(md.includes("✅ **Standup** — 3 commits"));
  });

  test("uses failure emoji for failed members", () => {
    const brief = makeBrief({
      verdict: "attention",
      attentionCount: 1,
      members: [
        { label: "Deps", status: "failed", attention: true },
      ],
    });
    const md = renderBriefMarkdown(brief, strings);
    assert.ok(md.includes("❌ **Deps**"));
  });

  test("includes duration when present", () => {
    const md = renderBriefMarkdown(makeBrief(), strings);
    assert.ok(md.includes("(120 ms)"));
    assert.ok(md.includes("(300 ms)"));
  });

  test("attention verdict includes count", () => {
    const brief = makeBrief({
      verdict: "attention",
      attentionCount: 3,
    });
    const md = renderBriefMarkdown(brief, strings);
    assert.ok(md.includes("**Needs attention (3)**"));
  });

  test("omits headline when member has none", () => {
    const brief = makeBrief({
      members: [{ label: "Quick", status: "ok", attention: false }],
    });
    const md = renderBriefMarkdown(brief, strings);
    assert.ok(md.includes("✅ **Quick**"));
    assert.ok(!md.includes("✅ **Quick** —"));
  });
});

describe("export drift guard", () => {
  test("HTML export renders every BriefMember field that has a value", () => {
    const brief = makeBrief({
      members: [{
        label: "Full Member",
        status: "failed",
        headline: "drift-check headline",
        attention: true,
        durationMs: 4567,
        reportPath: "/reports/drift.md",
      }],
    });
    const html = renderBriefExportHtml(brief, strings);
    assert.ok(html.includes("Full Member"), "label rendered");
    assert.ok(html.includes("drift-check headline"), "headline rendered");
    assert.ok(html.includes("4.6 s"), "durationMs rendered");
  });

  test("Markdown export renders every BriefMember field that has a value", () => {
    const brief = makeBrief({
      members: [{
        label: "Full Member",
        status: "failed",
        headline: "drift-check headline",
        attention: true,
        durationMs: 4567,
        reportPath: "/reports/drift.md",
      }],
    });
    const md = renderBriefMarkdown(brief, strings);
    assert.ok(md.includes("Full Member"), "label rendered");
    assert.ok(md.includes("drift-check headline"), "headline rendered");
    assert.ok(md.includes("4.6 s"), "durationMs rendered");
    assert.ok(md.includes("❌"), "failed status rendered");
  });
});
